# Usa la imagen base oficial de Python
FROM python:latest

# Establece el directorio de trabajo en /app
WORKDIR /app

RUN mkdir -p /app/routers

# Copia el contenido actual del directorio al directorio de trabajo
COPY /routers/health_agency_router.py /app/routers/



