apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: pod-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: pod-2
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: servicio-3
spec:
  selector:
    app: pod-3
  ports:
  - protocol: TCP
    port: 82
    targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: service-4
spec:
  selector:
    app: pod-4
  ports:
  - protocol: TCP
    port: 83
    targetPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: service-5
spec:
  selector:
    app: pod-5
  ports:
  - protocol: TCP
    port: 84
    targetPort: 8084

---
apiVersion: v1
kind: Service
metadata:
  name: service-6
spec:
  selector:
    app: pod-6
  ports:
  - protocol: TCP
    port: 85
    targetPort: 8085


---
apiVersion: v1
kind: Service
metadata:
  name: service-7
spec:
  selector:
    app: pod-7
  ports:
  - protocol: TCP
    port: 86
    targetPort: 8086


---
apiVersion: v1
kind: Service
metadata:
  name: service-8
spec:
  selector:
    app: pod-8
  ports:
  - protocol: TCP
    port: 87
    targetPort: 8087


---
apiVersion: v1
kind: Service
metadata:
  name: service-9
spec:
  selector:
    app: pod-9
  ports:
  - protocol: TCP
    port: 88
    targetPort: 8088


---
apiVersion: v1
kind: Service
metadata:
  name: service-10
spec:
  selector:
    app: pod-10
  ports:
  - protocol: TCP
    port: 89
    targetPort: 8089

  
---
apiVersion: v1
kind: Service
metadata:
  name: service-11
spec:
  selector:
    app: pod-11
  ports:
  - protocol: TCP
    port: 90
    targetPort: 8090


---
apiVersion: v1
kind: Service
metadata:
  name: service-12
spec:
  selector:
    app: pod-12
  ports:
  - protocol: TCP
    port: 91
    targetPort: 8091


---
apiVersion: v1
kind: Service
metadata:
  name: service-13
spec:
  selector:
    app: pod-13
  ports:
  - protocol: TCP
    port: 92
    targetPort: 8092